apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-redis
  template:
    metadata:
      labels:
        app: azure-redis
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: azure-redis
          image: redis:latest
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          ports:
            - containerPort: 6379
              name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-redis
spec:
  ports:
  - port: 6379
  selector:
    app: azure-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-app-server
  template:
    metadata:
      labels:
        app: azure-app-server
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azure-app-server
        image: rgenovevo/scc2223-app:latest
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
        ports:
        - containerPort: 80
        env:
        - name: REDIS_URL
          value: "azure-redis"
        - name: COSMOSDB_URL
          value: "https://scc2345576.documents.azure.com:443/"
        - name: COSMOSDB_KEY
          value: "CNZeJSeeFbVncj5xseYeFOznkT2xxNT7q16hBsFSlCoiWl2fT2vBocu4PFN2wGBaCEjU24JSj4kZACDbOqWXUg=="
        - name: COSMOSDB_DATABASE
          value: "scc23db45576"
        volumeMounts:
        - mountPath: "/mnt/vol"
          name: mediavolume
      volumes:
      - name: mediavolume
        persistentVolumeClaim:
          claimName: azure-managed-disk
---
apiVersion: v1
kind: Service
metadata:
  name: azure-app-server
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: azure-app-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi